In [140]:
pwd

'C:\\Users\\user\\OneDrive\\Desktop\\FINAL_THESIS'

In [141]:
import pandas as pd
from imblearn.over_sampling import SMOTE

In [142]:
df = pd.read_csv('Updated_planet.csv')
df

default_flag  sy_snum  sy_pnum  discoverymethod    pl_orbper  \
0                 1        2        1                8   326.030000   
1                 0        2        1                8   389.426657   
2                 0        1        1                8   452.823313   
3                 1        1        1                8   516.219970   
4                 0        1        1                8   516.220000   
...             ...      ...      ...              ...          ...   
26821             1        2        3                8  1276.460000   
26822             0        2        3                8  1319.000000   
26823             0        2        3                8  1278.100000   
26824             1        1        1                8   136.750000   
26825             0        1        1                8   136.750000   

       pl_orbsmax  pl_msinie  pl_orbeccen      st_teff     st_rad  st_mass  \
0         1.29000  6165.6000     0.231000  4742.000000  19.000000    2.700   
1         1.21000  5434.7000     0.180667  4565.666667  22.596667    2.600   
2         1.51000  3432.4000     0.130333  4389.333333  26.193333    1.700   
3         1.53000  4684.8142     0.080000  4213.000000  29.790000    2.780   
4         1.54000  3337.0700     0.080000  4340.000000  24.080000    1.800   
...           ...        ...          ...          ...        ...      ...   
26821     2.51329  1313.2200     0.298700  6105.510000   1.560000    1.300   
26822     2.57000  1255.3800     0.269000  6105.510000   1.600000    1.225   
26823     2.53000  1312.6379     0.267000  6105.510000   1.640000    1.150   
26824     0.68000   890.0000     0.000000  4780.000000  12.000000    2.200   
26825     0.58000   642.0000     0.000000  4780.000000  12.000000    1.400   

        st_logg   sy_dist  
0      2.310000   93.1846  
1      2.183333   93.1846  
2      2.056667  125.3210  
3      1.930000  125.3210  
4      1.600000  125.3210  
...         ...       ...  
26821  4.070000   13.4054  
26822  4.070000   13.4054  
26823  4.070000   13.4054  
26824  2.660000   56.1858  
26825  2.660000   56.1858  

[26826 rows x 13 columns]

In [143]:
df.isnull().sum()

default_flag       0
sy_snum            0
sy_pnum            0
discoverymethod    0
pl_orbper          0
pl_orbsmax         0
pl_msinie          0
pl_orbeccen        0
st_teff            0
st_rad             0
st_mass            0
st_logg            0
sy_dist            0
dtype: int64

In [144]:
Y = df['sy_pnum']
X = df.drop('sy_pnum',axis = 1)

In [145]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import  train_test_split
X_train,X_test,Y_train,Y_test = \
train_test_split(X,Y,test_size = 0.3,random_state = 10)

In [146]:
model1 = KNeighborsClassifier()
model1.fit(X_train,Y_train)
Y_predict = model1.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_predict))

0.8378479125248509


### Implementing the SMOTE technique for balancing the data.

In [147]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train_smote,Y_train_smote = smote.fit_sample(X_train,Y_train)
from collections import Counter
print('Before Smote:',Counter(Y_train))
print('After Smote:',Counter(Y_train_smote))

Before Smote: Counter({1: 9520, 2: 4604, 3: 2505, 4: 1294, 5: 657, 6: 149, 8: 39, 7: 10})
After Smote: Counter({1: 9520, 3: 9520, 4: 9520, 5: 9520, 8: 9520, 2: 9520, 6: 9520, 7: 9520})


In [148]:
model1.fit(X_train_smote,Y_train_smote)
Y_predict = model1.predict(X_test)
print(accuracy_score(Y_test,Y_predict))


0.8348658051689861


### Implementing the Logistic Regression over the balance dataset

##### Since Logistic Regression works best on the Binary distribution class, therefore the accuracy of the Logistic regression is pretty low which is about 22% and here we can observe that precision score of Number 1 planet is quite good as compared to another planet in classification report.

In [149]:
from  sklearn.linear_model import LogisticRegression
modellog = LogisticRegression()

In [163]:
modellog.fit(X_train_smote,Y_train_smote)
Y_predictlog = modellog.predict(X_test)

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [164]:
print(accuracy_score(Y_test,Y_predictlog))

0.2055168986083499


In [165]:
print(classification_report(Y_test,Y_predictlog))

              precision    recall  f1-score   support

           1       0.62      0.35      0.44      4233
           2       0.20      0.02      0.04      1901
           3       0.13      0.07      0.09      1014
           4       0.01      0.00      0.00       545
           5       0.01      0.02      0.02       253
           6       0.02      0.73      0.04        77
           7       0.00      0.00      0.00         9
           8       0.01      0.94      0.02        16

    accuracy                           0.21      8048
   macro avg       0.13      0.27      0.08      8048
weighted avg       0.39      0.21      0.26      8048



#### Now lets see if we get any changes in the accuracy by implementing ove vs rest technique for logistic regression, we cans see below this technique also didnt work well over the balanced data for the multi classification, the classification work well for the binary classification only.

In [166]:
clflog = LogisticRegression(random_state=0, multi_class='ovr')

In [167]:
clflog.fit(X_train_smote,Y_train_smote)

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable

LogisticRegression(multi_class='ovr', random_state=0)

In [168]:
Y_predictlogovr = clflog.predict(X_test)

In [169]:
print(accuracy_score(Y_test,Y_predictlogovr))

0.21980616302186878


In [170]:
print(classification_report(Y_test,Y_predictlogovr))

              precision    recall  f1-score   support

           1       0.63      0.35      0.45      4233
           2       0.32      0.04      0.07      1901
           3       0.14      0.09      0.11      1014
           4       0.03      0.01      0.02       545
           5       0.11      0.20      0.14       253
           6       0.02      0.73      0.04        77
           7       0.73      0.89      0.80         9
           8       0.01      0.94      0.02        16

    accuracy                           0.22      8048
   macro avg       0.25      0.40      0.21      8048
weighted avg       0.43      0.22      0.27      8048



In [159]:
clflog = LogisticRegression(random_state=0, multi_class='ovr')

In [160]:
clflog.fit(X_train_smote,Y_train_smote)

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable

LogisticRegression(multi_class='ovr', random_state=0)

In [161]:
Y_predictlogovr = clflog.predict(X_test)

In [162]:
print(accuracy_score(Y_test,Y_predictlogovr))

0.21980616302186878


In [151]:
print(accuracy_score(Y_test,Y_predictlog)*100)

20.55168986083499


In [152]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [153]:
print(classification_report(Y_test,Y_predictlog)*100)

              precision    recall  f1-score   support

           1       0.62      0.35      0.44      4233
           2       0.20      0.02      0.04      1901
           3       0.13      0.07      0.09      1014
           4       0.01      0.00      0.00       545
           5       0.01      0.02      0.02       253
           6       0.02      0.73      0.04        77
           7       0.00      0.00      0.00         9
           8       0.01      0.94      0.02        16

    accuracy                           0.21      8048
   macro avg       0.13      0.27      0.08      8048
weighted avg       0.39      0.21      0.26      8048
              precision    recall  f1-score   support

           1       0.62      0.35      0.44      4233
           2       0.20      0.02      0.04      1901
           3       0.13      0.07      0.09      1014
           4       0.01      0.00      0.00       545
           5       0.01      0.02      0.02       253
           6       0.02  

In [154]:
print(confusion_matrix(Y_test,Y_predictlog)*100)

[[146400  10400  26600   4000  21200 132100   9700  72900]
 [ 42800   4600  12400   3300   7700  63300   2400  53600]
 [ 21600   5600   6700    100   4800  35900    600  26100]
 [ 15200   1000   1200    100   1000  23300      0  12700]
 [  9300    400   2400      0    500   6600   1800   4300]
 [     0    800   1000    100      0   5600      0    200]
 [   100      0    100      0      0    100      0    600]
 [   100      0      0      0      0      0      0   1500]]


### Implementing the support classifier

#### Support vector classifier works great on linear

In [155]:
from sklearn.svm import SVC

In [156]:
modelsvc2 = SVC()

In [157]:
modelsvc2.fit(X_train_smote,Y_train_smote)

SVC()

In [158]:
y_pred_svm2 = modelsvc.predict(X_test)

AttributeError: 'SVC' object has no attribute 'shape_fit_'

In [134]:
print(accuracy_score(Y_test,y_pred_svm2)*100)

NameError: name 'y_pred_svm2' is not defined

In [86]:
Y.value_counts()

1    13753
2     6505
3     3519
4     1839
5      910
6      226
8       55
7       19
Name: sy_pnum, dtype: int64

In [124]:
print(X_train_smote.shape,Y_train_smote.shape)
print(X_test.shape,Y_test.shape)

(76160, 12) (76160,)
(8048, 12) (8048,)


In [125]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD

In [126]:
kerasmodel = Sequential()
kerasmodel.add(Dense(12,input_dim = 12,activation = 'relu',kernel_initializer='he_uniform'))
kerasmodel.add(Dense(10,activation = 'relu',kernel_initializer='he_uniform'))
kerasmodel.add(Dense(8,activation = 'relu',kernel_initializer='he_uniform'))
kerasmodel.add(Dense(1,activation = 'softmax'))

In [127]:
kerasmodel.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [128]:
kerasmodel.fit(X_train_smote,Y_train_smote,epochs = 25,batch_size = 10)

Epoch 1/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 2/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 3/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 4/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 5/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 6/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 7/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 8/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 9/25
7616/7616 [==============================] - 8s 1ms/step - loss: -53.3745 - accuracy: 0.1250
Epoch 10/25
7616/7616 [==============================] - 10s 1ms

In [135]:
_,accuracy = kerasmodel.evaluate(X_train_smote,Y_train_smote)

2380/2380 [==============================] - 2s 1ms/step - loss: -53.3715 - accuracy: 0.1250


In [136]:
print('train accuracy:%.2f' %(accuracy*100))

train accuracy:12.50


In [137]:
y_predkeras = kerasmodel.predict_classes(X_test)
accuracy_score(Y_test,y_predkeras)*100

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


52.5969184890656

In [87]:
smote = SMOTE(sampling_strategy = 'minority')
X_Sm,Y_SM = smote.fit_sample(X,Y)

In [88]:
Y_SM.value_counts()

7    13753
1    13753
2     6505
3     3519
4     1839
5      910
6      226
8       55
Name: sy_pnum, dtype: int64

In [89]:
x_train,x_test,y_train,y_test = train_test_split(X_Sm,Y_SM,test_size = 0.3,random_state = 10,stratify = Y_SM)

In [90]:
y_train.value_counts()

7    9627
1    9627
2    4554
3    2463
4    1287
5     637
6     158
8      39
Name: sy_pnum, dtype: int64

In [91]:
y_test.value_counts()

7    4126
1    4126
2    1951
3    1056
4     552
5     273
6      68
8      16
Name: sy_pnum, dtype: int64

In [92]:
from  sklearn.linear_model import LogisticRegression
modellogn = LogisticRegression()

In [93]:
modellogn.fit(X_Sm,Y_SM)
Y_predictlogn = modellogn.predict(x_test)

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [94]:
print(accuracy_score(Y_test,Y_predictlogn)*100)

ValueError: Found input variables with inconsistent numbers of samples: [8048, 12168]

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
modeldecision = DecisionTreeClassifier()

In [20]:
modeldecision.fit(X_train_smote,Y_train_smote)
Decison_predict = modeldecision.predict(X_test)

In [21]:
print(accuracy_score(Y_test,Decison_predict)*100)

92.06013916500993


In [22]:
from sklearn.ensemble import RandomForestClassifier

Classifier = RandomForestClassifier(n_estimators=20, random_state=0)
Classifier.fit(X_train_smote,Y_train_smote)
y_pred2 = Classifier.predict(X_test)

In [23]:
print(accuracy_score(Y_test,y_pred2)*100)

95.91202783300199


In [24]:
from sklearn.svm import SVC

In [25]:
modelsvc = SVC()

In [26]:
modelsvc.fit(X_train_smote,Y_train_smote)

SVC()

In [27]:
y_pred_svm = modelsvc.predict(X_test)

In [28]:
print(accuracy_score(Y_test,y_pred_svm)*100)

20.750497017892645


In [29]:
from  xgboost import XGBClassifier

In [30]:
XGBClassifier()

XGBClassifier(base_score=None, booster=None, colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=None, gamma=None,
              gpu_id=None, importance_type='gain', interaction_constraints=None,
              learning_rate=None, max_delta_step=None, max_depth=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              random_state=None, reg_alpha=None, reg_lambda=None,
              scale_pos_weight=None, subsample=None, tree_method=None,
              validate_parameters=None, verbosity=None)

In [31]:
modelXGB = XGBClassifier()
modelXGB.fit(X_train_smote,Y_train_smote)

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:06:54] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [32]:
y_pred_XGB = modelXGB.predict(X_test)

In [33]:
print(accuracy_score(Y_test,y_pred_XGB)*100)

94.61978131212724


In [34]:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier(DecisionTreeClassifier(),n_estimators = 5,learning_rate = 1)

In [35]:
adb.fit(X_train_smote,Y_train_smote)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), learning_rate=1,
                   n_estimators=5)

In [36]:
y_pred_adb = adb.predict(X_test)

In [37]:
print(accuracy_score(Y_test,y_pred_adb)*100)

91.82405566600397


In [38]:
print(X_train_smote.shape,Y_train_smote.shape)
print(X_test.shape,Y_test.shape)

(76160, 12) (76160,)
(8048, 12) (8048,)


In [39]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD

Using TensorFlow backend.


In [40]:
kerasmodel = Sequential()
kerasmodel.add(Dense(12,input_dim = 12,activation = 'relu',kernel_initializer='he_uniform'))
kerasmodel.add(Dense(10,activation = 'relu',kernel_initializer='he_uniform'))
kerasmodel.add(Dense(8,activation = 'relu',kernel_initializer='he_uniform'))
kerasmodel.add(Dense(1,activation = 'softmax'))

In [43]:
kerasmodel.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [47]:
clf = LogisticRegression(random_state=0, multi_class='ovr')

In [49]:
#model = clf.fit(X_train_smote,Y_train_smote)

c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\user\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable

In [50]:
#y_pred_log = model.predict(X_test)

In [51]:
#print(accuracy_score(Y_test,y_pred_log)*100)

21.259940357852884
